name: ZombieMMO
version: 0.0.1
main: tomasborsje.plugin.zombiemmo.ZombieMMOPlugin
author: Tomas Borsje
api-version: 1.19

commands:
  zombiesgive:
    description: Gives ZombiesMMO items.
    usage: /<command> <item_id>
    permission: zombiemmo.admin