name: ZombiesMMO
version: 0.0.3
main: tomasborsje.plugin.zombiesmmo.ZombiesMMO
author: Tomas Borsje
api-version: 1.19

commands:
  zombiesgive:
    description: Gives ZombiesMMO items.
    usage: /<command> <item_id>
    permission: zombiesmmo.admin
  zombiesspawn:
    description: Spawns ZombiesMMO entities.
    usage: /<command> <entity_id>
    permission: zombiesmmo.admin